entero n1,n2,n3
cadena [20]correo
cadena [20]clave 
inicio
  n1<-3
	 mientras (n1>0) haga
	escriba "ingrese su usuario"
	llamar nueva_linea
	lea correo
	escriba "ingrese su clave"
	llamar nueva_linea 
	lea clave
		si  (correo="lucas@ma.com") y (clave="123") entonces
		escriba "bienvenid@"
		n1<-0
		sino
		llamar nueva_linea
		escriba "ususario o clave erroneo" 
		llamar nueva_linea
		escriba "tienes",n1-1,"intentos"
	fin si
	n1<-n1-1
    	fin mientras 
    fin