entero n1,n2,r,p,Q
caracter continuar
inicio
	repita
	p<-1
		mientras (p<=2) haga
		escriba "suma:",P
		llamar nueva_linea
		escriba "ingrese el primer numer numero para la suma"
		llamar nueva_linea
		lea n1
		escriba "ingrese el segundo numero para la suma"
		llamar nueva_linea
		lea n2
		r<-n1+n2
		escriba "la suma es:", r
		llamar nueva_linea
		p<-p+1
		fin mientras
	escriba "¿desea terminar? ingrese N"
	lea continuar
	hasta (continuar='N')
	
fin	